### ISSUE TITLE
Update to 5.1.26

### ISSUE THREAD

**Issue by gusbemacbe** [vboxme/Portable-VirtualBox#52] opened 2017-08-01 23:51 UTC
Hello,

I want to update from 5.1.8 to 5.1.26. Please, update the software.

**Comment by p060477** [comment] 2017-08-02 06:30
it is simply useless cause since 3 years it is not possible to use network bridged but only NAT..
due to the lack of the presence of its developer..mr Runar Buvick..
what a pity..
what a shame..
:(

**Comment by gusbemacbe** [comment] 2017-08-02 06:57
Are you speaking of @runarbu? Strange, he made the latest commit in May this year.

**Comment by p060477** [comment] 2017-08-02 07:42
o yes is very active..except on this very BIG BUG of the impossibility of using the network bridged..
the BUG is still there since 3 years..
what a shame..
:(

**Comment by Megachip** [comment] 2017-08-10 16:48
duplicate of https://github.com/vboxme/Portable-VirtualBox/issues/53

**Closed by Megachip** 2017-08-10 16:48 UTC
Labels: duplicate
